on: 
  pull_request:
    branches:
      - master

name: Test and Validate ARM Templates

env:
  LOCATION: westeurope
  RESOURCE_GROUP_TEST: rg-validation

jobs:
  test_arm_templates:
    runs-on: ubuntu-latest
    name: Test deployment and Run Azure Resource Manager Template Toolkit
    steps:
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'dev1'

      - name: Azure CLI Validate Deployment
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az group create --location $LOCATION --name $RESOURCE_GROUP_TEST
            az group deployment validate --resource-group $RESOURCE_GROUP_TEST --template-file $GITHUB_WORKSPACE/azuredeploy.json
            az group delete --resource-group $RESOURCE_GROUP_TEST --yes --no-wait 

      - name: Run Azure Resource Manager Template Toolkit
        uses: ./.github/actions
        id: action
